# Generated by Django 6.0.8 on 2026-08-12 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('interest', models.CharField(choices=[('visit', 'Planejar visita'), ('ministries', 'Ministérios'), ('counseling', 'Aconselhamento'), ('events', 'Eventos')], max_length=20, verbose_name='interesse')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('contacted', models.BooleanField(default=False, verbose_name='contatado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('kind', models.CharField(max_length=60, verbose_name='tipo')),
                ('location', models.CharField(max_length=160, verbose_name='local')),
                ('expected_attendance', models.PositiveIntegerField(default=0, verbose_name='público esperado')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('leader_name', models.CharField(max_length=120, verbose_name='líder')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('recruiting', 'Precisa de voluntários')], default='active', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'ministério',
                'verbose_name_plural': 'ministérios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('leadership', 'Liderança'), ('visitor', 'Visitante'), ('new', 'Novo'), ('away', 'Afastado')], default='active', max_length=20, verbose_name='status')),
                ('frequency', models.PositiveSmallIntegerField(default=0, verbose_name='frequência')),
                ('baptized', models.BooleanField(default=False, verbose_name='batizado')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.ministry')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('description', models.CharField(max_length=180, verbose_name='descrição')),
                ('category', models.CharField(max_length=80, verbose_name='categoria')),
                ('kind', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=10, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.member')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
