# Generated by Django 6.0.8 on 2026-08-12 01:56

import django.db.models.deletion
from django.db import migrations, models
from datetime import timedelta


def import_existing_events(apps, schema_editor):
    ChurchEvent = apps.get_model('core', 'Event')
    CalendarEvent = apps.get_model('swingtime', 'Event')
    EventType = apps.get_model('swingtime', 'EventType')
    Occurrence = apps.get_model('swingtime', 'Occurrence')

    for event in ChurchEvent.objects.all():
        event_type = EventType.objects.filter(label=event.kind[:50]).first()
        if event_type is None:
            base = ''.join(character for character in event.kind.lower() if character.isalnum())[:4] or 'evt'
            abbreviation = base
            counter = 1
            while EventType.objects.filter(abbr=abbreviation).exists():
                suffix = str(counter)
                abbreviation = f'{base[:4 - len(suffix)]}{suffix}'
                counter += 1
            event_type = EventType.objects.create(abbr=abbreviation, label=event.kind[:50])

        calendar_event = CalendarEvent.objects.create(
            title=event.title,
            description=event.description,
            event_type=event_type,
        )
        Occurrence.objects.create(
            event=calendar_event,
            start_time=event.starts_at,
            end_time=event.starts_at + timedelta(hours=2),
        )
        event.calendar_event_id = calendar_event.pk
        event.save(update_fields=['calendar_event'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('swingtime', '0002_alter_occurrence_options_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_event', to='swingtime.event', verbose_name='evento da agenda'),
        ),
        migrations.RunPython(import_existing_events, migrations.RunPython.noop),
    ]
