# Generated by Django 6.0.8 on 2026-08-12 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classify_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    AccessProfile = apps.get_model('core', 'AccessProfile')
    profiles = [
        AccessProfile(user=user, role='board' if user.is_staff else 'member')
        for user in User.objects.all()
    ]
    AccessProfile.objects.bulk_create(profiles, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_calendar_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pastor', 'Pastor'), ('board', 'Diretoria'), ('deacon', 'Diácono'), ('secretary', 'Secretário'), ('treasurer', 'Tesoureiro'), ('member', 'Membro'), ('visitor', 'Visitante'), ('child', 'Criança')], default='member', max_length=20, verbose_name='classificação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de acesso',
                'verbose_name_plural': 'perfis de acesso',
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.RunPython(classify_existing_users, migrations.RunPython.noop),
    ]
