# Generated by Django 6.0.8 on 2026-08-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='usuarios/%Y/%m/', verbose_name='foto'),
        ),
    ]
