# Generated by Django 6.0.8 on 2026-08-12 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accessprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, verbose_name='referência')),
                ('text', models.TextField(max_length=3000, verbose_name='texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='favoritado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versículo favorito',
                'verbose_name_plural': 'versículos favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reference'), name='unique_bible_favorite_reference')],
            },
        ),
        migrations.CreateModel(
            name='BibleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, verbose_name='referência')),
                ('content', models.TextField(max_length=3000, verbose_name='anotação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anotação bíblica',
                'verbose_name_plural': 'anotações bíblicas',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reference'), name='unique_bible_note_reference')],
            },
        ),
    ]
