# Generated by Django 6.0.8 on 2026-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_progress_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço completo'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_1_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='nascimento do filho 1'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_1_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome do filho 1'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_2_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='nascimento do filho 2'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_2_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome do filho 2'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_3_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='nascimento do filho 3'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_3_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome do filho 3'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_4_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='nascimento do filho 4'),
        ),
        migrations.AddField(
            model_name='member',
            name='child_4_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome do filho 4'),
        ),
        migrations.AddField(
            model_name='member',
            name='divorce_comments',
            field=models.TextField(blank=True, verbose_name='comentários sobre o divórcio'),
        ),
        migrations.AddField(
            model_name='member',
            name='divorced',
            field=models.BooleanField(blank=True, null=True, verbose_name='divorciado'),
        ),
        migrations.AddField(
            model_name='member',
            name='education',
            field=models.CharField(blank=True, max_length=120, verbose_name='escolaridade'),
        ),
        migrations.AddField(
            model_name='member',
            name='home_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone residencial'),
        ),
        migrations.AddField(
            model_name='member',
            name='married',
            field=models.BooleanField(blank=True, null=True, verbose_name='casado'),
        ),
        migrations.AddField(
            model_name='member',
            name='married_to_divorced',
            field=models.BooleanField(blank=True, null=True, verbose_name='casado com alguém divorciado'),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=120, verbose_name='profissão'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_divorce_comments',
            field=models.TextField(blank=True, verbose_name='comentários sobre o divórcio do cônjuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='wedding_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de casamento'),
        ),
        migrations.AddField(
            model_name='member',
            name='widow_comments',
            field=models.TextField(blank=True, verbose_name='comentários sobre a viuvez'),
        ),
        migrations.AddField(
            model_name='member',
            name='widowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='já passou por processo de viuvez'),
        ),
        migrations.AddField(
            model_name='member',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone comercial'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='celular'),
        ),
    ]
