# Generated by Django 6.0.8 on 2026-08-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_member_address_member_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='divorce_comments',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_divorce_comments',
        ),
        migrations.RemoveField(
            model_name='member',
            name='widow_comments',
        ),
    ]
