# Generated by Django 6.0.8 on 2026-08-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_member_divorce_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptism_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de batismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='church_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de entrada na igreja'),
        ),
        migrations.AddField(
            model_name='member',
            name='conversion_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de conversão'),
        ),
    ]
