# Generated by Django 6.0.8 on 2026-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_member_baptism_date_member_church_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='role',
            field=models.CharField(choices=[('pastor', 'Pastor'), ('board', 'Admin'), ('deacon', 'Diácono'), ('secretary', 'Secretário'), ('treasurer', 'Tesoureiro'), ('member', 'Membro'), ('visitor', 'Visitante'), ('child', 'Criança')], default='member', max_length=20, verbose_name='classificação'),
        ),
    ]
