# Generated by Django 6.0.8 on 2026-08-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_accessprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='subtítulo')),
                ('author_name', models.CharField(default='Pr. Washington Araujo', max_length=120, verbose_name='autor')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('cover_url', models.URLField(blank=True, verbose_name='capa')),
                ('purchase_url', models.URLField(blank=True, verbose_name='link de compra')),
                ('preview_url', models.URLField(blank=True, verbose_name='link de leitura')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço')),
                ('is_featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
