# Generated by Django 6.0.8 on 2026-08-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(default='about', editable=False, max_length=20, unique=True)),
                ('eyebrow', models.CharField(default='Nossa igreja', max_length=80, verbose_name='faixa')),
                ('heading', models.CharField(default='Conheça a identidade da Canaã.', max_length=140, verbose_name='título')),
                ('intro', models.TextField(default='Firmados nas Escrituras e comprometidos com o Evangelho, somos uma família que adora, serve e caminha unida para a glória de Deus.', verbose_name='introdução')),
                ('highlight_1_title', models.CharField(default='Ensino que transforma', max_length=120, verbose_name='destaque 1')),
                ('highlight_1_text', models.TextField(default='Conteúdo bíblico aplicado à vida, à família e ao serviço cristão.', verbose_name='texto 1')),
                ('highlight_2_title', models.CharField(default='Relacionamentos que acolhem', max_length=120, verbose_name='destaque 2')),
                ('highlight_2_text', models.TextField(default='Uma comunidade preparada para caminhar ao seu lado em cada estação.', verbose_name='texto 2')),
                ('highlight_3_title', models.CharField(default='Serviço com propósito', max_length=120, verbose_name='destaque 3')),
                ('highlight_3_text', models.TextField(default='Ministérios para desenvolver dons e impactar pessoas dentro e fora da igreja.', verbose_name='texto 3')),
            ],
            options={
                'verbose_name': 'conteúdo da página Nossa igreja',
                'verbose_name_plural': 'conteúdo da página Nossa igreja',
            },
        ),
        migrations.CreateModel(
            name='ChurchHistoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(default='history', editable=False, max_length=20, unique=True)),
                ('eyebrow', models.CharField(default='Histórico da igreja', max_length=80, verbose_name='faixa')),
                ('heading', models.CharField(default='A caminhada da Canaã ao longo do tempo.', max_length=140, verbose_name='título')),
                ('intro', models.TextField(default='Uma linha do tempo para registrar a origem, o crescimento e a missão que continuam moldando a igreja até hoje.', verbose_name='introdução')),
                ('milestone_1_title', models.CharField(default='Fundação', max_length=120, verbose_name='marco 1')),
                ('milestone_1_text', models.TextField(default='A igreja nasceu do desejo de cultivar uma comunidade centrada em Cristo e comprometida com a Palavra.', verbose_name='texto 1')),
                ('milestone_2_title', models.CharField(default='Crescimento', max_length=120, verbose_name='marco 2')),
                ('milestone_2_text', models.TextField(default='A família da fé se expandiu com novos ministérios, discipulado e presença ativa na cidade.', verbose_name='texto 2')),
                ('milestone_3_title', models.CharField(default='Hoje', max_length=120, verbose_name='marco 3')),
                ('milestone_3_text', models.TextField(default='Seguimos servindo com ensino, adoração, ação social e cuidado pastoral contínuo.', verbose_name='texto 3')),
            ],
            options={
                'verbose_name': 'conteúdo da página Histórico',
                'verbose_name_plural': 'conteúdo da página Histórico',
            },
        ),
    ]
