# Generated by Django 6.0.8 on 2026-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_churchaboutpage_churchhistorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchhistorypage',
            name='photo_1_url',
            field=models.URLField(blank=True, verbose_name='foto 1'),
        ),
        migrations.AddField(
            model_name='churchhistorypage',
            name='photo_2_url',
            field=models.URLField(blank=True, verbose_name='foto 2'),
        ),
        migrations.AddField(
            model_name='churchhistorypage',
            name='photo_3_url',
            field=models.URLField(blank=True, verbose_name='foto 3'),
        ),
    ]
